### ISSUE TITLE
依赖安装错误

### ISSUE THREAD

**Issue by ghost** [zzfly256/RyShop#4]
` [Symfony\Component\Process\Exception\RuntimeException]
  The Process class relies on proc_open, which is not available on your PHP installation.
`
php56 72 
多台服务器测试均报错

**Comment by zzfly256** [comment]
`The Process class relies on proc_open` , `not available on your PHP installation`
尝试按照提示打开拓展吧

**Comment by 1760714192** [comment]
已解决 起因为函数禁用
